# loki-config.yml
auth_enabled: false

server:
  http_listen_port: 3100

common:
  storage:
    s3:
      endpoint: s3.eu-west-3.amazonaws.com
      region: eu-west-3
      bucket_name: votre-nom-logs-loki
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2024-01-01
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  aws:
    s3: s3://votre-nom-logs-loki
    region: eu-west-3
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    shared_store: s3

chunk_store_config:
  max_look_back_period: 336h

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h